"""Generate docs/generated/* from the working-tree contract."""
from __future__ import annotations

import csv
import io
import json
from collections import Counter
from pathlib import Path

from jsonschema import Draft202012Validator

from .compile import compile_contract, resolve_all_profiles
from .functions import added_functions, field_facets, source_card, source_functions
from .schema_gen import field_schema, item_defs
from .sources import Sources, load_sources
from .util import ContractError, load_yaml

GEN_DIR = Path("docs/generated")
BANNER = ("<!-- GENERATED by `bdc generate` from field_catalog/field_catalog.yaml, vocabularies/, profiles/ and "
          "mappings/. Do not edit by hand. -->\n\n")
CSV_COLUMNS = ["path", "group", "type", "availability", "required", "vocabulary", "status", "maturity", "origin",
               "since", "function_tags", "key_role", "serves", "serves_from_source", "serves_added", "facets", "card", "argument_role",
               "definition_zh", "data_source_zh", "downstream_zh", "constraints", "ambiguities", "source_ref"]
FIELD_EXAMPLES = Path("docs/field_examples.yaml")
FIELD_CLASSIFICATION = Path("docs/field_classification.yaml")


def _md(s) -> str:
    return str(s if s is not None else "").replace("|", "\\|").replace("\n", " ")


def load_field_examples(root: Path, contract: dict) -> dict:
    """Require a curated, schema-valid value for every field; version identity stays automatic."""
    path = root / FIELD_EXAMPLES
    if not path.is_file():
        raise ContractError(f"missing {FIELD_EXAMPLES}")
    examples = load_yaml(path)
    if not isinstance(examples, dict):
        raise ContractError(f"{FIELD_EXAMPLES} must map field paths to example values")
    automatic = {"common.schema_name": contract["name"], "common.schema_version": contract["version"]}
    expected = {f["path"] for f in contract["fields"]} - automatic.keys()
    missing, extra = expected - examples.keys(), examples.keys() - expected
    if missing or extra:
        raise ContractError(f"{FIELD_EXAMPLES}: missing examples {sorted(missing)}; unknown or automatic fields {sorted(extra)}")
    examples.update(automatic)
    defs = item_defs(contract)
    for f in contract["fields"]:
        schema = {**field_schema(contract, f), "$defs": defs}
        errors = list(Draft202012Validator(schema).iter_errors(examples[f["path"]]))
        if errors:
            raise ContractError(f"{FIELD_EXAMPLES}: {f['path']}: {errors[0].message}")
    return examples


def load_field_classification(root: Path, contract: dict) -> dict:
    """Load the user's four multi-select documentation tags and require explicit coverage."""
    path = root / FIELD_CLASSIFICATION
    if not path.is_file():
        raise ContractError(f"missing {FIELD_CLASSIFICATION}")
    classification = load_yaml(path)
    if not isinstance(classification, dict) or classification.get("classification_format") != 1:
        raise ContractError(f"{FIELD_CLASSIFICATION}: expected classification_format: 1")
    tags, fields = classification.get("tags"), classification.get("fields")
    if not isinstance(tags, dict) or set(tags) != {"research_1", "research_2", "iteration", "general"}:
        raise ContractError(f"{FIELD_CLASSIFICATION}: expected the four functional categories")
    for code, spec in tags.items():
        if not isinstance(spec, dict) or not all(isinstance(spec.get(k), str) and spec[k].strip()
                                                for k in ("label_zh", "description_zh")):
            raise ContractError(f"{FIELD_CLASSIFICATION}: {code} needs a label and description")
    if not isinstance(fields, dict):
        raise ContractError(f"{FIELD_CLASSIFICATION}: fields must map paths to tag lists")
    expected = {f["path"] for f in contract["fields"]}
    missing, extra = expected - fields.keys(), fields.keys() - expected
    if missing or extra:
        raise ContractError(f"{FIELD_CLASSIFICATION}: missing fields {sorted(missing)}; unknown fields {sorted(extra)}")
    for field, selected in fields.items():
        if not isinstance(selected, list) or not selected or \
                any(not isinstance(tag, str) or tag not in tags for tag in selected) or len(selected) != len(set(selected)):
            raise ContractError(f"{FIELD_CLASSIFICATION}: {field} needs a nonempty list of distinct valid tags")
    return classification


def _classification_label(classification: dict, path: str) -> str:
    return "、".join(classification["tags"][tag]["label_zh"] for tag in classification["fields"][path])


def field_definitions_md(contract: dict, examples: dict, classification: dict) -> str:
    fields, codes = contract["fields"], contract["codes"]
    out = ["<!-- GENERATED by `bdc generate` from field_catalog/field_catalog.yaml, vocabularies/ "
           "and docs/field_examples.yaml / docs/field_classification.yaml. Do not edit by hand. -->\n\n",
           f"# 字段定义与示例 — {contract['name']} {contract['version']}\n\n",
           "[中文 README](../../README.md) · [English README](../../README.en.md) · "
           "[详细字段字典](field_dictionary.md) · [CSV 下载](field_dictionary.csv) · "
           "[按功能组织的字段表](field_functions.md)\n\n",
           f"共 **{len(fields)}** 个字段；每个字段均列出原始定义、功能分类、数据类型、JSON 取值示意和填写要求。"
           "定义直接读取规范源文件，示例与功能标签按字段维护。\n\n",
           "## 如何阅读\n\n",
           "- `group.field` 表示嵌套字段路径，JSON 中应写成 `group` 对象下的 `field` 键。\n",
           "- 示例列展示**字段的 JSON 值**，包含字符串引号、数组和对象结构。所有示例均为教学用途的合成示意，"
           "不代表真实论文结果、有效外部标识或授权。各行独立，不能拼成一条完整记录。\n",
           "- 未报告的信息省略，不使用 `null`、空字符串、空数组或空对象；不要把示例当默认值。\n",
           "- 示例按单字段 Schema 校验；完整记录仍需满足[跨字段规则](rules.md)及引用关系。\n",
           "- 可获得性：" + "；".join(f"`{k}` {v['label_zh']}" for k, v in codes['availability'].items()) + "。这些代码不是质量分数。\n",
           "- 必填：" + "；".join(f"`{k}` {v['label_zh']}" for k, v in codes['requirement'].items()) +
           "。`C` 的具体触发条件见跨字段规则和所用画像。\n",
           "- 成熟度：`verified` 为已验证基线；`provisional` 为待确认的新增语义。"
           "带 `AMB-*` 的字段还需参考[歧义登记](ambiguities.md)。\n\n",
           "例如，`common.crop_name` 与 `common.trait_names` 的嵌套写法如下（仅为结构片段）：\n\n",
           '```json\n{"common": {"crop_name": "rice", "trait_names": ["株高"]}}\n```\n\n',
           "## 功能分类（可多选）\n\n按字段的直接用途标注以下四类，一个字段可同时拥有多个标签。"
           "`common`、`agent`、`skills` 等是字段存储分组，功能标签可跨组重叠。\n\n"
           "| 标签 | 功能说明 |\n|---|---|\n"]
    for spec in classification["tags"].values():
        out.append(f"| {_md(spec['label_zh'])} | {_md(spec['description_zh'])} |\n")
    out.append(f"\n例如，`common.schema_version` 标为“{_classification_label(classification, 'common.schema_version')}”，"
               f"`agent.evidence_record_ids` 标为“{_classification_label(classification, 'agent.evidence_record_ids')}”。\n\n"
               "## 字段分组导航\n\n| 字段组 | 字段数 | 用途 |\n|---|---:|---|\n")
    for group, spec in contract["groups"].items():
        count = sum(f["group"] == group for f in fields)
        out.append(f"| [{group}](#{group}) | {count} | {_md(spec['purpose_zh'])} |\n")
    for group, spec in contract["groups"].items():
        out.append(f"\n## {group}\n\n**{spec['title_zh']}** — {spec['purpose_zh']}。\n\n"
                   "| 字段路径 | 类型 | 含义 | 功能分类（可多选） | JSON 取值示意 | 填写要求（可获得性 / 必填） |\n|---|---|---|---|---|---|\n")
        for f in (f for f in fields if f["group"] == group):
            example = json.dumps(examples[f["path"]], ensure_ascii=False, allow_nan=False)
            # A multi-backtick fence also handles literal backticks inside a future example.
            fence = "`"
            while fence in example:
                fence += "`"
            notes = [f"{f['availability']} / {f['required']}", f["maturity"]]
            if f.get("vocabulary"):
                notes.append(f"词表：{f['vocabulary']}")
            constraints = f.get("constraints") or {}
            for key, label in (("minimum", "≥"), ("maximum", "≤"), ("pattern", "格式：")):
                if key in constraints:
                    notes.append(f"{label}`{constraints[key]}`" if key == "pattern" else f"{label}{constraints[key]}")
            notes.extend(f.get("ambiguities") or [])
            if f["status"] != "active":
                notes.append("已弃用")
            out.append(f"| `{f['path']}` | `{f['type']}` | {_md(f['definition_zh'])} | "
                       f"{_md(_classification_label(classification, f['path']))} | "
                       f"{fence}{_md(example)}{fence} | {_md('；'.join(notes))} |\n")
    out.append("\n## 更新本文档\n\n含义以 [field_catalog/field_catalog.yaml](../../field_catalog/field_catalog.yaml) 为准；"
               "示例维护在 [docs/field_examples.yaml](../field_examples.yaml)，"
               "功能分类维护在 [docs/field_classification.yaml](../field_classification.yaml)。规范名称和版本的示例自动生成。"
               "新增字段时需同时补齐示例与功能标签，再运行 `bdc generate`。`bdc check --strict` 会检查分类与示例覆盖、"
               "字段类型与约束、本文档及其他生成文档是否同步。\n")
    return "".join(out)


def field_dictionary_md(contract: dict, classification: dict) -> str:
    fields = contract["fields"]
    out = [BANNER, f"# 字段字典 — {contract['name']} {contract['version']}\n\n",
           "[查看字段定义与逐字段 JSON 示例](field_definitions.md)。\n\n",
           f"{contract['title_zh']}。共 **{len(fields)}** 个字段"
           f"（现行 {sum(f['status'] == 'active' for f in fields)}）。记录布局：`group.field` → 嵌套 JSON；"
           "未报告字段一律省略。\n\n",
           "可获得性：" + "；".join(f"`{k}` {v['label_zh']}" for k, v in contract["codes"]["availability"].items()) +
           "。" + contract["codes"].get("availability_note_zh", "") + "\n\n"]
    groups = list(contract["groups"])
    avail = list(contract["codes"]["availability"])
    out.append("| 字段组 | " + " | ".join(avail) + " | 合计 | 说明 |\n|---|" + "---:|" * (len(avail) + 1) + "---|\n")
    for g in groups:
        c = Counter(f["availability"] for f in fields if f["group"] == g)
        out.append(f"| `{g}` | " + " | ".join(str(c.get(a, 0)) for a in avail) +
                   f" | {sum(c.values())} | {_md(contract['groups'][g]['purpose_zh'])} |\n")
    out.append("\n")
    for g in groups:
        gf = [f for f in fields if f["group"] == g]
        out.append(f"## `{g}` — {contract['groups'][g]['title_zh']}（{len(gf)}）\n\n")
        out.append("| 字段路径 | 类型 | 可获得性 | 必填 | 词表 | 成熟度/来源 | 功能分类（可多选） | 键角色 | 服务功能 | 定义 | 数据来源 | 下游用途 |\n")
        out.append("|---|---|---|---|---|---|---|---|---|---|---|---|\n")
        for f in gf:
            flag = f["maturity"] + "/" + "+".join(f["origin"]) + ("" if f["status"] == "active" else " ⚠弃用")
            amb = f" （{', '.join(f['ambiguities'])}）" if f.get("ambiguities") else ""
            out.append(f"| `{f['path']}` | {f['type']} | {f['availability']} | {f['required']} | "
                       f"{_md(f.get('vocabulary', ''))} | {flag} | {_md(_classification_label(classification, f['path']))} | {_role_label(contract, f)} | "
                       f"{_serves_label(contract, f)} | {_md(f['definition_zh'])}{amb} | "
                       f"{_md(f.get('data_source_zh'))} | {_md(f.get('downstream_zh'))} |\n")
        out.append("\n")
    return "".join(out)


def _role_label(contract: dict, f: dict) -> str:
    spec = contract["codes"]["key_role"].get(f.get("key_role"), {})
    extra = []
    if f.get("argument_role"):
        extra.append(contract["codes"]["argument_role"][f["argument_role"]]["label_zh"])
    if f.get("card"):
        extra.append(contract["codes"]["card"][f["card"]]["label_zh"])
    return f"{spec.get('label_zh', f.get('key_role'))}" + (f"（{'，'.join(extra)}）" if extra else "")


def _serves_label(contract: dict, f: dict) -> str:
    """Function labels; repository additions (not stated by the sources) are marked with ⁺."""
    added = set(added_functions(contract, f))
    short = {k: v.get("short_zh") or v["label_zh"].split("：")[0].split("（")[0] for k, v in contract["codes"]["function"].items()}
    return "、".join(short[fn] + ("⁺" if fn in added else "") for fn in f.get("serves") or [])


def field_functions_md(contract: dict) -> str:
    """Every key: what it does (key_role), which of the four functions it serves, and for what (facets)."""
    codes, fields = contract["codes"], contract["fields"]
    funcs, roles = codes["function"], codes["key_role"]
    out = [BANNER, f"# 字段的作用与功能归属 — {contract['name']} {contract['version']}\n\n",
           "每个键标注 **键角色**（它在记录里做什么，以及落到知识图谱、关系库、三元组、问答语料时的形态）和 **服务功能**"
           "（课题二、课题三、派生、自身迭代）。功能的分面取自 `sources/project/research_contents.md`；字段的分面 = 键角色的分面 ∩ 该字段服务的功能。"
           "下表中标 ⁺ 的功能由仓库补充。" + _md(codes.get("function_note_zh", ""))
           + " 设计说明与用法见 `docs/field_functions.md`。\n\n"]
    out.append("## 四项功能\n\n| 功能 | 说明 | 分面 | 字段数 | 来源标注 | 仓库补充 |\n|---|---|---|---:|---:|---:|\n")
    for code, spec in funcs.items():
        serving = [f for f in fields if code in (f.get("serves") or [])]
        from_src = sum(code in source_functions(contract, f) for f in serving)
        facets = "；".join(f"`{k}` {v['label_zh']}" for k, v in (spec.get("facets") or {}).items())
        out.append(f"| `{code}` {spec['label_zh']} | {_md(spec['description_zh'])} | {facets} | {len(serving)} | "
                   f"{from_src} | {len(serving) - from_src} |\n")
    out.append("\n## 键角色\n\n| 类别 | 键角色 | 说明 | 知识图谱 | 关系库 | 三元组 | 问答/语料 | 分面 | 字段数 |\n"
               "|---|---|---|---|---|---|---|---|---:|\n")
    fams = codes.get("key_role_family") or {}
    for code, spec in roles.items():
        n = sum(f.get("key_role") == code for f in fields)
        pr = spec.get("projection") or {}
        facets = "；".join(f"{fn}: {'/'.join(v)}" for fn, v in (spec.get("facets") or {}).items())
        out.append(f"| {fams.get(spec.get('family'), {}).get('label_zh', '')} | `{code}` {spec['label_zh']} | "
                   f"{_md(spec['description_zh'])} | {_md(pr.get('kg'))} | {_md(pr.get('rdb'))} | {_md(pr.get('triple'))} | "
                   f"{_md(pr.get('qa_corpus'))} | {facets} | {n} |\n")
    arg = codes.get("argument_role") or {}
    if arg:
        out.append(f"\n## 证据链要素（TRACE）\n\n{_md(codes.get('argument_role_source', ''))}\n\n"
                   "| 要素 | 框架 | 说明 | 字段 |\n|---|---|---|---|\n")
        for code, spec in arg.items():
            ps = [f"`{f['path']}`" for f in fields if f.get("argument_role") == code]
            out.append(f"| `{code}` {spec['label_zh']} / {spec.get('label_en', '')} | {spec.get('framework', '')} | "
                       f"{_md(spec['description_zh'])} | {', '.join(ps)} |\n")
    cards = codes.get("card") or {}
    if cards:
        out.append(f"\n## 卡片（课题二/三）\n\n{_md(codes.get('card_note_zh', ''))}\n\n| 卡片 | 字段（* 为来源标注） |\n|---|---|\n")
        for code, spec in cards.items():
            ps = [f"`{f['path']}`" + ("*" if source_card(contract, f) == code else "")
                  for f in fields if f.get("card") == code]
            out.append(f"| `{code}` {spec['label_zh']} | {', '.join(ps)} |\n")
    for code, spec in funcs.items():
        serving = [f for f in fields if code in (f.get("serves") or [])]
        out.append(f"\n## {spec['label_zh']}（`{code}`，{len(serving)} 个字段）\n\n{_md(spec['description_zh'])}\n\n")
        for facet, fspec in (spec.get("facets") or {}).items():
            ps = [f for f in serving if facet in field_facets(contract, f).get(code, [])]
            out.append(f"- **{fspec['label_zh']}**（`{facet}`，{len(ps)}）：{_md(fspec['description_zh'])}\n")
        out.append("\n| 字段 | 键角色 | 分面 | 来源 | 卡片/要素 | 定义 |\n|---|---|---|---|---|---|\n")
        order = list(roles)
        for f in sorted(serving, key=lambda f: (order.index(f["key_role"]), f["path"])):
            facets = "/".join(field_facets(contract, f).get(code, []))
            origin = "仓库补充" if code in added_functions(contract, f) else "来源"
            extra = "，".join(x for x in (codes["card"][f["card"]]["label_zh"] if f.get("card") else "",
                                         arg[f["argument_role"]]["label_zh"] if f.get("argument_role") else "") if x)
            out.append(f"| `{f['path']}` | {roles[f['key_role']]['label_zh']} | {facets} | {origin} | {extra} | "
                       f"{_md(f['definition_zh'])} |\n")
    return "".join(out)


def field_dictionary_csv(contract: dict, classification: dict) -> str:
    buf = io.StringIO()
    w = csv.DictWriter(buf, fieldnames=CSV_COLUMNS, lineterminator="\n")
    w.writeheader()
    for f in contract["fields"]:
        row = {k: f.get(k, "") for k in CSV_COLUMNS}
        row["function_tags"] = _classification_label(classification, f["path"])
        row["origin"] = "+".join(f["origin"])
        row["constraints"] = ";".join(f"{k}={v}" for k, v in (f.get("constraints") or {}).items()
                                      if k in ("minimum", "maximum", "pattern"))
        row["ambiguities"] = ",".join(f.get("ambiguities") or [])
        row["serves"] = ",".join(f.get("serves") or [])
        row["serves_from_source"] = ",".join(source_functions(contract, f))
        row["serves_added"] = ",".join(added_functions(contract, f))
        row["facets"] = ";".join(f"{fn}:{'+'.join(fs)}" for fn, fs in field_facets(contract, f).items())
        w.writerow(row)
    return buf.getvalue()


def profiles_md(contract: dict, profiles: dict) -> str:
    out = [BANNER, f"# 画像 — {contract['name']} {contract['version']}\n\n",
           "画像从契约中选择字段并（对抽取画像）声明非抽取字段由哪条命名规则确定性生成。"
           "角色：`extract` 模型抽取并附证据；`document` 文档级抽取；`provenance` 证据定位（由模型的 evidence 提供）；"
           "`system` 管线确定性生成；`normalized` 由原文值确定性换算；`generated` 仅当后端实际提供时写入；"
           "`field` 非抽取画像中的普通字段。\n\n"]
    for name, p in profiles.items():
        out.append(f"## `{name}` — {p['title_zh']}\n\n{_md(p['description_zh'])}\n\n")
        if len(p["extends_chain"]) > 1:
            out.append(f"继承链：{' → '.join(p['extends_chain'])}\n\n")
        out.append(f"字段数：**{p['counts']['total']}**；按角色：" +
                   "，".join(f"{k} {v}" for k, v in p["counts"]["by_role"].items()) +
                   "；按可获得性：" + "，".join(f"{k} {v}" for k, v in p["counts"]["by_availability"].items()) +
                   "\n\n")
        if p.get("model_record_kinds"):
            out.append("模型可产出的记录类型：" + ", ".join(f"`{k}`" for k in p["model_record_kinds"]) + "\n\n")
        if p.get("fill_rules"):
            out.append("命名填充规则（须由 Skill 实现）：" + ", ".join(f"`{r}`" for r in p["fill_rules"]) + "\n\n")
        roles = Counter(f["role"] for f in p["fields"])
        for role in sorted(roles):
            paths = [f["path"] for f in p["fields"] if f["role"] == role]
            out.append(f"<details><summary>{role}（{len(paths)}）</summary>\n\n" +
                       ", ".join(f"`{x}`" for x in paths) + "\n\n</details>\n\n")
    return "".join(out)


def vocabularies_md(contract: dict) -> str:
    bound: dict[str, list[str]] = {}
    for f in contract["fields"]:
        if f.get("vocabulary"):
            bound.setdefault(f["vocabulary"], []).append(f["path"])
    out = [BANNER, f"# 受控词表 — {contract['name']} {contract['version']}\n\n",
           "执行级别：`error` 写入 JSON Schema enum；`warning` 由校验器提示；`open` 仅为建议值。"
           "`code_status: proposed` 表示代码由仓库提议、待确认（AMB-010）。\n\n"]
    for name, voc in sorted(contract["vocabularies"].items()):
        out.append(f"## `{name}` — {voc.get('title_zh', '')}\n\n")
        if voc.get("vocabulary_type") == "unit_conversion":
            out.append(f"单位换算表（{voc.get('code_status')}）。\n\n| 量纲 | 规范单位 | 可换算单位 | 别名 |\n|---|---|---|---|\n")
            for dim, spec in voc["dimensions"].items():
                out.append(f"| {dim} | `{spec['canonical']}` | " + ", ".join(f"`{u}`" for u in spec["units"]) +
                           " | " + ", ".join(f"`{a}`→`{t}`" for a, t in (spec.get("aliases") or {}).items()) + " |\n")
            out.append("\n")
            continue
        out.append(f"执行：`{voc.get('enforcement')}`；闭合：`{voc.get('closure')}`；代码来源：`{voc.get('code_status')}`；"
                   f"绑定字段：{', '.join(f'`{p}`' for p in bound.get(name, [])) or '（无）'}\n\n")
        src = voc.get("source") or {}
        if src.get("quote_zh"):
            out.append(f"> 来源：{_md(src['quote_zh'])}（`{src.get('ref')}`）\n\n")
        out.append("| 代码 | 中文标签 | 说明 |\n|---|---|---|\n")
        for v in voc["values"]:
            extra = []
            if v.get("grain") is not None and "grain" in v:
                extra.append(f"粒度 {v['grain']}")
            if v.get("aliases"):
                extra.append("别名 " + "/".join(v["aliases"]))
            if v.get("code_status"):
                extra.append(v["code_status"])
            if v.get("description_zh"):
                extra.append(v["description_zh"])
            out.append(f"| `{v['code']}` | {_md(v.get('label_zh', ''))} | {_md('；'.join(extra))} |\n")
        out.append("\n")
    return "".join(out)


def rules_md(contract: dict) -> str:
    out = [BANNER, f"# 跨字段规则 — {contract['name']} {contract['version']}\n\n",
           "`basis`：explicit 来源明确陈述；definitional 由定义直接推出；inferred 据字段分组推断（一律 warning）。\n\n",
           "| ID | 类型 | 级别 | 依据 | 规则 | 来源 |\n|---|---|---|---|---|---|\n"]
    for r in contract["rules"]:
        out.append(f"| {r['id']} | {r['kind']} | {r['severity']} | {r['basis']} | {_md(r['title_zh'])} | "
                   f"{_md(r['source_zh'])} |\n")
    return "".join(out)


def ambiguities_md(contract: dict, mappings: dict[str, dict]) -> str:
    out = [BANNER, "# 歧义与决策登记\n\n",
           "来源材料未明确或相互矛盾之处。`open` 未决；`provisional` 暂行方案待确认；`decided` 仓库已决策；"
           "`resolved` 已由数据负责人确认。\n\n## 契约层（field_catalog.yaml）\n\n",
           "| ID | 状态 | 主题 | 发现 | 处理 |\n|---|---|---|---|---|\n"]
    for a in contract["ambiguities"]:
        out.append(f"| {a['id']} | {a['status']} | {_md(a['title_zh'])} | {_md(a['finding_zh'])} | "
                   f"{_md(a['resolution_zh'])} |\n")
    for name, m in sorted(mappings.items()):
        issues = m.get("issues") or []
        if not issues:
            continue
        out.append(f"\n## 映射层（mappings/{name}.yaml）\n\n| ID | 主题 | 发现 | 处理 |\n|---|---|---|---|\n")
        for i in issues:
            out.append(f"| {i['id']} | {_md(i['title_zh'])} | {_md(i['finding_zh'])} | {_md(i['resolution_zh'])} |\n")
    return "".join(out)


def load_mappings(root: Path) -> dict[str, dict]:
    return {p.stem: load_yaml(p) for p in sorted((root / "mappings").glob("*.yaml"))}


def generate_docs(src: Sources | None = None) -> dict[str, str]:
    """Return generated contents keyed by paths relative to the repository root."""
    src = src or load_sources()
    contract = compile_contract(src)
    profiles = resolve_all_profiles(contract, src.profiles)
    mappings = load_mappings(src.root)
    classification = load_field_classification(src.root, contract)
    docs = {
        "field_definitions.md": field_definitions_md(contract, load_field_examples(src.root, contract), classification),
        "field_dictionary.md": field_dictionary_md(contract, classification),
        "field_dictionary.csv": field_dictionary_csv(contract, classification),
        "field_functions.md": field_functions_md(contract),
        "profiles.md": profiles_md(contract, profiles),
        "vocabularies.md": vocabularies_md(contract),
        "rules.md": rules_md(contract),
        "ambiguities.md": ambiguities_md(contract, mappings),
    }
    return {str(GEN_DIR / name): text for name, text in docs.items()}


def write_docs(root: Path, docs: dict[str, str]) -> list[str]:
    changed = []
    for rel, text in docs.items():
        p = root / rel
        if not p.exists() or p.read_text(encoding="utf-8") != text:
            p.parent.mkdir(parents=True, exist_ok=True)
            p.write_text(text, encoding="utf-8")
            changed.append(rel)
    return changed


def write_xlsx(root: Path, out_path: Path) -> Path:
    """Excel field dictionary (optional dependency openpyxl). Not committed: binary and non-deterministic."""
    from openpyxl import Workbook
    from openpyxl.styles import Font

    src = load_sources(root)
    contract = compile_contract(src)
    wb = Workbook()
    ws = wb.active
    ws.title = "fields"
    ws.append(CSV_COLUMNS)
    for cell in ws[1]:
        cell.font = Font(bold=True)
    rows = list(csv.DictReader(io.StringIO(field_dictionary_csv(contract, load_field_classification(root, contract)))))
    for row in rows:
        ws.append([row[c] for c in CSV_COLUMNS])
    ws.freeze_panes = "B2"
    meta = wb.create_sheet("contract")
    for k in ("name", "version", "title_zh", "source_digest"):
        meta.append([k, contract[k]])
    out_path.parent.mkdir(parents=True, exist_ok=True)
    wb.save(out_path)
    return out_path
