"""Generate human-facing documentation (docs/generated/*) from the working-tree contract."""
from __future__ import annotations

import csv
import io
from collections import Counter
from pathlib import Path

from .compile import compile_contract, resolve_all_profiles
from .sources import Sources, load_sources
from .util import load_yaml

GEN_DIR = Path("docs/generated")
BANNER = ("<!-- GENERATED by `bdc generate` from field_catalog/field_catalog.yaml, vocabularies/, profiles/ and "
          "mappings/. Do not edit by hand. -->\n\n")
CSV_COLUMNS = ["path", "group", "type", "availability", "required", "vocabulary", "status", "maturity", "origin",
               "since", "definition_zh", "data_source_zh", "downstream_zh", "constraints", "ambiguities",
               "source_ref"]


def _md(s) -> str:
    return str(s if s is not None else "").replace("|", "\\|").replace("\n", " ")


def field_dictionary_md(contract: dict) -> str:
    fields = contract["fields"]
    out = [BANNER, f"# 字段字典 — {contract['name']} {contract['version']}\n\n",
           f"{contract['title_zh']}。共 **{len(fields)}** 个字段"
           f"（现行 {sum(f['status'] == 'active' for f in fields)}）。记录布局：`group.field` → 嵌套 JSON；"
           "未报告字段一律省略。\n\n",
           "可获得性：" + "；".join(f"`{k}` {v['label_zh']}" for k, v in contract["codes"]["availability"].items()) +
           "。" + contract["codes"].get("availability_note_zh", "") + "\n\n"]
    groups = list(contract["groups"])
    avail = list(contract["codes"]["availability"])
    out.append("| 字段组 | " + " | ".join(avail) + " | 合计 | 说明 |\n|---|" + "---:|" * (len(avail) + 1) + "---|\n")
    for g in groups:
        c = Counter(f["availability"] for f in fields if f["group"] == g)
        out.append(f"| `{g}` | " + " | ".join(str(c.get(a, 0)) for a in avail) +
                   f" | {sum(c.values())} | {_md(contract['groups'][g]['purpose_zh'])} |\n")
    out.append("\n")
    for g in groups:
        gf = [f for f in fields if f["group"] == g]
        out.append(f"## `{g}` — {contract['groups'][g]['title_zh']}（{len(gf)}）\n\n")
        out.append("| 字段路径 | 类型 | 可获得性 | 必填 | 词表 | 成熟度/来源 | 定义 | 数据来源 | 下游用途 |\n")
        out.append("|---|---|---|---|---|---|---|---|---|\n")
        for f in gf:
            flag = f["maturity"] + "/" + "+".join(f["origin"]) + ("" if f["status"] == "active" else " ⚠弃用")
            amb = f" （{', '.join(f['ambiguities'])}）" if f.get("ambiguities") else ""
            out.append(f"| `{f['path']}` | {f['type']} | {f['availability']} | {f['required']} | "
                       f"{_md(f.get('vocabulary', ''))} | {flag} | {_md(f['definition_zh'])}{amb} | "
                       f"{_md(f.get('data_source_zh'))} | {_md(f.get('downstream_zh'))} |\n")
        out.append("\n")
    return "".join(out)


def field_dictionary_csv(contract: dict) -> str:
    buf = io.StringIO()
    w = csv.DictWriter(buf, fieldnames=CSV_COLUMNS, lineterminator="\n")
    w.writeheader()
    for f in contract["fields"]:
        row = {k: f.get(k, "") for k in CSV_COLUMNS}
        row["origin"] = "+".join(f["origin"])
        row["constraints"] = ";".join(f"{k}={v}" for k, v in (f.get("constraints") or {}).items()
                                      if k in ("minimum", "maximum", "pattern"))
        row["ambiguities"] = ",".join(f.get("ambiguities") or [])
        w.writerow(row)
    return buf.getvalue()


def profiles_md(contract: dict, profiles: dict) -> str:
    out = [BANNER, f"# 画像 — {contract['name']} {contract['version']}\n\n",
           "画像从契约中选择字段并（对抽取画像）声明非抽取字段由哪条命名规则确定性生成。"
           "角色：`extract` 模型抽取并附证据；`document` 文档级抽取；`provenance` 证据定位（由模型的 evidence 提供）；"
           "`system` 管线确定性生成；`normalized` 由原文值确定性换算；`generated` 仅当后端实际提供时写入；"
           "`field` 非抽取画像中的普通字段。\n\n"]
    for name, p in profiles.items():
        out.append(f"## `{name}` — {p['title_zh']}\n\n{_md(p['description_zh'])}\n\n")
        if len(p["extends_chain"]) > 1:
            out.append(f"继承链：{' → '.join(p['extends_chain'])}\n\n")
        out.append(f"字段数：**{p['counts']['total']}**；按角色：" +
                   "，".join(f"{k} {v}" for k, v in p["counts"]["by_role"].items()) +
                   "；按可获得性：" + "，".join(f"{k} {v}" for k, v in p["counts"]["by_availability"].items()) +
                   "\n\n")
        if p.get("model_record_kinds"):
            out.append("模型可产出的记录类型：" + ", ".join(f"`{k}`" for k in p["model_record_kinds"]) + "\n\n")
        if p.get("fill_rules"):
            out.append("命名填充规则（须由 Skill 实现）：" + ", ".join(f"`{r}`" for r in p["fill_rules"]) + "\n\n")
        roles = Counter(f["role"] for f in p["fields"])
        for role in sorted(roles):
            paths = [f["path"] for f in p["fields"] if f["role"] == role]
            out.append(f"<details><summary>{role}（{len(paths)}）</summary>\n\n" +
                       ", ".join(f"`{x}`" for x in paths) + "\n\n</details>\n\n")
    return "".join(out)


def vocabularies_md(contract: dict) -> str:
    bound: dict[str, list[str]] = {}
    for f in contract["fields"]:
        if f.get("vocabulary"):
            bound.setdefault(f["vocabulary"], []).append(f["path"])
    out = [BANNER, f"# 受控词表 — {contract['name']} {contract['version']}\n\n",
           "执行级别：`error` 写入 JSON Schema enum；`warning` 由校验器提示；`open` 仅为建议值。"
           "`code_status: proposed` 表示代码由仓库提议、待确认（AMB-010）。\n\n"]
    for name, voc in sorted(contract["vocabularies"].items()):
        out.append(f"## `{name}` — {voc.get('title_zh', '')}\n\n")
        if voc.get("vocabulary_type") == "unit_conversion":
            out.append(f"单位换算表（{voc.get('code_status')}）。\n\n| 量纲 | 规范单位 | 可换算单位 | 别名 |\n|---|---|---|---|\n")
            for dim, spec in voc["dimensions"].items():
                out.append(f"| {dim} | `{spec['canonical']}` | " + ", ".join(f"`{u}`" for u in spec["units"]) +
                           " | " + ", ".join(f"`{a}`→`{t}`" for a, t in (spec.get("aliases") or {}).items()) + " |\n")
            out.append("\n")
            continue
        out.append(f"执行：`{voc.get('enforcement')}`；闭合：`{voc.get('closure')}`；代码来源：`{voc.get('code_status')}`；"
                   f"绑定字段：{', '.join(f'`{p}`' for p in bound.get(name, [])) or '（无）'}\n\n")
        src = voc.get("source") or {}
        if src.get("quote_zh"):
            out.append(f"> 来源：{_md(src['quote_zh'])}（`{src.get('ref')}`）\n\n")
        out.append("| 代码 | 中文标签 | 说明 |\n|---|---|---|\n")
        for v in voc["values"]:
            extra = []
            if v.get("grain") is not None and "grain" in v:
                extra.append(f"粒度 {v['grain']}")
            if v.get("aliases"):
                extra.append("别名 " + "/".join(v["aliases"]))
            if v.get("code_status"):
                extra.append(v["code_status"])
            if v.get("description_zh"):
                extra.append(v["description_zh"])
            out.append(f"| `{v['code']}` | {_md(v.get('label_zh', ''))} | {_md('；'.join(extra))} |\n")
        out.append("\n")
    return "".join(out)


def rules_md(contract: dict) -> str:
    out = [BANNER, f"# 跨字段规则 — {contract['name']} {contract['version']}\n\n",
           "`basis`：explicit 来源明确陈述；definitional 由定义直接推出；inferred 据字段分组推断（一律 warning）。\n\n",
           "| ID | 类型 | 级别 | 依据 | 规则 | 来源 |\n|---|---|---|---|---|---|\n"]
    for r in contract["rules"]:
        out.append(f"| {r['id']} | {r['kind']} | {r['severity']} | {r['basis']} | {_md(r['title_zh'])} | "
                   f"{_md(r['source_zh'])} |\n")
    return "".join(out)


def ambiguities_md(contract: dict, mappings: dict[str, dict]) -> str:
    out = [BANNER, "# 歧义与决策登记\n\n",
           "来源材料未明确或相互矛盾之处。`open` 未决；`provisional` 暂行方案待确认；`decided` 仓库已决策；"
           "`resolved` 已由数据负责人确认。\n\n## 契约层（field_catalog.yaml）\n\n",
           "| ID | 状态 | 主题 | 发现 | 处理 |\n|---|---|---|---|---|\n"]
    for a in contract["ambiguities"]:
        out.append(f"| {a['id']} | {a['status']} | {_md(a['title_zh'])} | {_md(a['finding_zh'])} | "
                   f"{_md(a['resolution_zh'])} |\n")
    for name, m in sorted(mappings.items()):
        issues = m.get("issues") or []
        if not issues:
            continue
        out.append(f"\n## 映射层（mappings/{name}.yaml）\n\n| ID | 主题 | 发现 | 处理 |\n|---|---|---|---|\n")
        for i in issues:
            out.append(f"| {i['id']} | {_md(i['title_zh'])} | {_md(i['finding_zh'])} | {_md(i['resolution_zh'])} |\n")
    return "".join(out)


def load_mappings(root: Path) -> dict[str, dict]:
    return {p.stem: load_yaml(p) for p in sorted((root / "mappings").glob("*.yaml"))}


def generate_docs(src: Sources | None = None) -> dict[str, str]:
    src = src or load_sources()
    contract = compile_contract(src)
    profiles = resolve_all_profiles(contract, src.profiles)
    mappings = load_mappings(src.root)
    return {
        "field_dictionary.md": field_dictionary_md(contract),
        "field_dictionary.csv": field_dictionary_csv(contract),
        "profiles.md": profiles_md(contract, profiles),
        "vocabularies.md": vocabularies_md(contract),
        "rules.md": rules_md(contract),
        "ambiguities.md": ambiguities_md(contract, mappings),
    }


def write_docs(root: Path, docs: dict[str, str]) -> list[str]:
    d = root / GEN_DIR
    d.mkdir(parents=True, exist_ok=True)
    changed = []
    for rel, text in docs.items():
        p = d / rel
        if not p.exists() or p.read_text(encoding="utf-8") != text:
            p.write_text(text, encoding="utf-8")
            changed.append(rel)
    return changed


def write_xlsx(root: Path, out_path: Path) -> Path:
    """Excel field dictionary (optional dependency openpyxl). Not committed: binary and non-deterministic."""
    from openpyxl import Workbook
    from openpyxl.styles import Font

    src = load_sources(root)
    contract = compile_contract(src)
    wb = Workbook()
    ws = wb.active
    ws.title = "fields"
    ws.append(CSV_COLUMNS)
    for cell in ws[1]:
        cell.font = Font(bold=True)
    rows = list(csv.DictReader(io.StringIO(field_dictionary_csv(contract))))
    for row in rows:
        ws.append([row[c] for c in CSV_COLUMNS])
    ws.freeze_panes = "B2"
    meta = wb.create_sheet("contract")
    for k in ("name", "version", "title_zh", "source_digest"):
        meta.append([k, contract[k]])
    out_path.parent.mkdir(parents=True, exist_ok=True)
    wb.save(out_path)
    return out_path
